//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreServerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public int id { get; set; }
        public int product_id { get; set; }
        public int user_id { get; set; }
        public int amount { get; set; }
        public Nullable<float> total_price { get; set; }
    
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
