
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.storeserverlibrary.ArrayOfInventoryDTO;
import org.datacontract.schemas._2004._07.storeserverlibrary.ArrayOfProductDTO;
import org.datacontract.schemas._2004._07.storeserverlibrary.UserDTO;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IStoreService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.storeserverlibrary.ObjectFactory.class,
    org.tempuri.ObjectFactory.class
})
public interface IStoreService {


    /**
     * 
     * @param username
     * @return
     *     returns org.datacontract.schemas._2004._07.storeserverlibrary.UserDTO
     */
    @WebMethod(operationName = "Register", action = "http://tempuri.org/IStoreService/Register")
    @WebResult(name = "RegisterResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Register", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Register")
    @ResponseWrapper(localName = "RegisterResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RegisterResponse")
    public UserDTO register(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username);

    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns org.datacontract.schemas._2004._07.storeserverlibrary.UserDTO
     */
    @WebMethod(operationName = "Login", action = "http://tempuri.org/IStoreService/Login")
    @WebResult(name = "LoginResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Login", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginResponse")
    public UserDTO login(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @return
     *     returns org.datacontract.schemas._2004._07.storeserverlibrary.ArrayOfProductDTO
     */
    @WebMethod(operationName = "GetProducts", action = "http://tempuri.org/IStoreService/GetProducts")
    @WebResult(name = "GetProductsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetProducts", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetProducts")
    @ResponseWrapper(localName = "GetProductsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetProductsResponse")
    public ArrayOfProductDTO getProducts();

    /**
     * 
     * @param amount
     * @param productId
     * @param user
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "BuyProduct", action = "http://tempuri.org/IStoreService/BuyProduct")
    @WebResult(name = "BuyProductResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BuyProduct", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuyProduct")
    @ResponseWrapper(localName = "BuyProductResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BuyProductResponse")
    public Boolean buyProduct(
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        UserDTO user,
        @WebParam(name = "productId", targetNamespace = "http://tempuri.org/")
        Integer productId,
        @WebParam(name = "amount", targetNamespace = "http://tempuri.org/")
        Integer amount);

    /**
     * 
     * @param currentUser
     * @return
     *     returns org.datacontract.schemas._2004._07.storeserverlibrary.ArrayOfInventoryDTO
     */
    @WebMethod(operationName = "GetInventory", action = "http://tempuri.org/IStoreService/GetInventory")
    @WebResult(name = "GetInventoryResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetInventory", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInventory")
    @ResponseWrapper(localName = "GetInventoryResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInventoryResponse")
    public ArrayOfInventoryDTO getInventory(
        @WebParam(name = "currentUser", targetNamespace = "http://tempuri.org/")
        UserDTO currentUser);

    /**
     * 
     * @param userId
     * @return
     *     returns org.datacontract.schemas._2004._07.storeserverlibrary.UserDTO
     */
    @WebMethod(operationName = "FindUser", action = "http://tempuri.org/IStoreService/FindUser")
    @WebResult(name = "FindUserResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "FindUser", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FindUser")
    @ResponseWrapper(localName = "FindUserResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.FindUserResponse")
    public UserDTO findUser(
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        Integer userId);

}
